### ISSUE TITLE
Problem with Authentication

### ISSUE THREAD

**Issue by rlhelinski** [alastair/python-musicbrainzngs#153]
I'm having trouble using `musicbrainzngs.get_releases_in_collection()`. I've isolated the problem using the `examples/collection.py` script. The script works with the `--add` and `--remove` options, but if I only specify the collection as in `python collection.py rlhelinski 3a809fd0-8e27-4676-af45-f7799e914baa`, then I get the following exception:

```
Traceback (most recent call last):
  File "collection.py", line 121, in <module>
    show_collection(collection_id)
  File "collection.py", line 57, in show_collection
    result = musicbrainzngs.get_releases_in_collection(collection_id, limit=25)
  File "/home/ryan/mbcat/python-musicbrainzngs/musicbrainzngs/musicbrainz.py", line 1127, in get_releases_in_collection
    return _do_mb_query("collection", "%s/releases" % collection, [], params)
  File "/home/ryan/mbcat/python-musicbrainzngs/musicbrainzngs/musicbrainz.py", line 686, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "/home/ryan/mbcat/python-musicbrainzngs/musicbrainzngs/musicbrainz.py", line 386, in __call__
    return self.fun(*args, **kwargs)
  File "/home/ryan/mbcat/python-musicbrainzngs/musicbrainzngs/musicbrainz.py", line 651, in _mb_request
    resp = _safe_read(opener, req, body)
  File "/home/ryan/mbcat/python-musicbrainzngs/musicbrainzngs/musicbrainz.py", line 477, in _safe_read
    raise AuthenticationError(cause=exc)
musicbrainzngs.musicbrainz.AuthenticationError: caused by: HTTP Error 401: Unauthorized
```

*This problem goes away when I make the collection public* by checking `Allow other users to see this collection` on musicbrainz.org. I also checked: this is not the same exception that occurs if I mistype my password. 

I am using c515f453e542c9d0df900115986e2be4c82198cc. 

Thanks!

**Comment by alastair** [comment]
Fixed by #155
