### ISSUE TITLE
ValueError: at least one query term is required

### ISSUE THREAD

**Issue by nivong** [alastair/python-musicbrainzngs#177]
Noticed this in Headphones, and since it's the same pl file I thought why not create an issue here too.
https://github.com/rembo10/headphones/issues/2330

```
2015-08-14 13:57:46 ERROR Uncaught exception: Traceback (most recent call last):
File "/volume1/@appstore/headphones-custom/var/Headphones/headphones/logger.py", line 210, in new_run
old_run(args, *kwargs)
File "/usr/local/python/lib/python2.7/threading.py", line 763, in run
self.__target(self.__args, *self.__kwargs)
File "/volume1/@appstore/headphones-custom/var/Headphones/headphones/librarysync.py", line 330, in libraryScan
importer.artistlist_to_mbids(artist_list)
File "/volume1/@appstore/headphones-custom/var/Headphones/headphones/importer.py", line 63, in artistlist_to_mbids
results = mb.findArtist(artist, limit=1)
File "/volume1/@appstore/headphones-custom/var/Headphones/headphones/mb.py", line 101, in findArtist
artistResults = musicbrainzngs.search_artists(limit=limit, **criteria)['artist-list']
File "/usr/local/headphones-custom/var/Headphones/lib/musicbrainzngs/musicbrainz.py", line 927, in search_artists
return _do_mb_search('artist', query, fields, limit, offset, strict)
File "/usr/local/headphones-custom/var/Headphones/lib/musicbrainzngs/musicbrainz.py", line 777, in _do_mb_search
raise ValueError('at least one query term is required')
ValueError: at least one query term is required

Happens right after scanning my music directory.

**Comment by mineo** [comment]
Raising that exception is intentional if no non-empty query term is passed to a search function. If you believe that to be the case, please reopen this issue, but from the traceback and a (very) quick look at headphones' code it's not clear that this is really a fault in this library.
