### ISSUE TITLE
Get tracklist based on albumid

### ISSUE THREAD

**Issue by KeizerDev** [alastair/python-musicbrainzngs#181]
When doing some requests with the library like `m.get_artist_by_id()` I get something like:
```
{'artist': {'name': 'Pink Floyd', 'area': {'sort-name': 'United Kingdom', 'iso-3166-1-code-list': ['GB'], 'id': '8a754a16-0027-3a29-b6d7-2b40ea0481ed', 'name': 'United Kingdom'}, 'release-group-count': 302, 'country': 'GB', 'life-span': {'ended': 'true', 'begin': '1965', 'end': '2014'}, 'isni-list': ['0000000109397559'], 'release-group-list': [{'first-release-date': '1973-12-05', 'secondary-type-list': ['Compilation'], 'primary-type': 'Album', 'title': 'A Nice Pair', 'type': 'Compilation', 'id': '1a1387bd-ae1f-3024-8618-eeb2249f5538'}, {'first-release-date': '1975-09-12', 'title': 'Wish You Were Here', 'type': 'Album', 'id': '1a272023-10d3-38ee-bab3-317b55fcc21d', 'primary-type': 'Album'}, {'first-release-date': '1977-01-23', 'title': 'Animals', 'type': 'Album', 'id': '20c77fb4-1c9f-33c8-9d7e-c4977f11e847', 'primary-type': 'Album'}, {'first-release-date': '2014-11-07', 'title': 'The Endless River', 'type': 'Album', 'id': '38b4c840-16ce-40fa-b7c0-a354b7c87178', 'primary-type': 'Album'}, {'first-release-date': '1987-09-07', 'title': 'A Momentary Lapse of Reason', 'type': 'Album', 'id': '4940b8aa-898b-3e60-9992-94e073bab6f6', 'primary-type': 'Album'}, {'first-release-date': '1971-10-31', 'title': 'Meddle', 'type': 'Album', 'id': '4e98c9b4-92f6-3049-b9da-a1088b623672', 'primary-type': 'Album'}, {'first-release-date': '1971', 'title': 'First Time In Japan', 'type': 'Album', 'id': '5b195040-6ee8-4075-82e6-ea1f6c9f0c72', 'primary-type': 'Album'}, {'first-release-date': '', 'title': 'The Complete BBC Sessions', 'type': 'Album', 'id': '62d0e1e4-90e6-47e4-ad20-fd3a4004a928', 'primary-type': 'Album'}, {'first-release-date': '1967-07-07', 'title': 'The Piper at the Gates of Dawn', 'type': 'Album', 'id': '6792b6d1-4e65-3c3c-9d20-d08aa1dcfc60', 'primary-type': 'Album'}, {'first-release-date': '1981-11-23', 'secondary-type-list': ['Compilation'], 'primary-type': 'Album', 'title': 'A Collection of Great Dance Songs', 'type': 'Compilation', 'id': '70300163-5e9c-32b9-b49f-bfb25e5aebee'}, {'first-release-date': '2002', 'title': 'A Saucerful of Secrets [Mono Edition Bootleg]', 'type': 'Album', 'id': '7c66df58-e8ae-4d3c-9f3e-0ca341b79705', 'primary-type': 'Album'}, {'first-release-date': '2011-11-01', 'title': 'Thirteen', 'type': 'Album', 'id': '80e44774-d85b-4ada-9ff9-55d75f811343', 'primary-type': 'Album'}, {'first-release-date': '1971-05-14', 'secondary-type-list': ['Compilation'], 'primary-type': 'Album', 'title': 'Relics', 'type': 'Compilation', 'id': '83593465-37cc-3d6f-a3d2-61c81e3c2be6'}
```
But now I want to get all the tracks of the album using the `id`. 
So I've tried all of the following but none of them works:
```
    # result = m.get_work_by_id(evt.target.get_selected_items()[0]['id'], includes=["recordings"])

    # print m.get_label_by_id(evt.target.get_selected_items()[0]['id'])
    print m.get_releases_by_discid(evt.target.get_selected_items()[0]['id'], includes=["artists", "recordings"])
    # print m.get_release_group_by_id(evt.target.get_selected_items()[0]['id'])
    # print m.get_recording_by_id(evt.target.get_selected_items()[0]['id'])
    # print m.get_work_by_id(evt.target.get_selected_items()[0]['id'])
```
I'm pretty sure the id is right.

Thanks in advance

**Comment by mineo** [comment]
What's the id you're passing in?

**Comment by mineo** [comment]
Also, a [disc id](https://musicbrainz.org/doc/Disc_ID) is not the same thing as an [mbid](https://musicbrainz.org/doc/MusicBrainz_Identifier). If all you have is an mbid, use [get_release_by_id](https://python-musicbrainzngs.readthedocs.org/en/latest/api/#musicbrainzngs.get_release_by_id).

**Comment by KeizerDev** [comment]
I'm using the album `mbid` and that's the only one I have.
Now when I'm using this: 
```
#    print m.get_release_by_id(evt.target.get_selected_items()[0]['id'], includes=["artists", "recordings"])
#    print m.get_release_by_id(evt.target.get_selected_items()[0]['id'])
```
I get an 404:
```
ID: 1a1387bd-ae1f-3024-8618-eeb2249f5538

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gui/spec.py", line 79, in handler
    action(event)   # just call the user function
  File "./steeb.pyw", line 24, in get_tracks
    print m.get_release_by_id(evt.target.get_selected_items()[0]['id'])
  File "/usr/lib/python2.7/site-packages/musicbrainzngs/musicbrainz.py", line 803, in get_release_by_id
    return _do_mb_query("release", id, includes, params)
  File "/usr/lib/python2.7/site-packages/musicbrainzngs/musicbrainz.py", line 669, in _do_mb_query
    return _mb_request(path, 'GET', auth_required, args=args)
  File "/usr/lib/python2.7/site-packages/musicbrainzngs/musicbrainz.py", line 374, in __call__
    return self.fun(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/musicbrainzngs/musicbrainz.py", line 634, in _mb_request
    resp = _safe_read(opener, req, body)
  File "/usr/lib/python2.7/site-packages/musicbrainzngs/musicbrainz.py", line 460, in _safe_read
    raise ResponseError(cause=exc)
musicbrainzngs.musicbrainz.ResponseError: caused by: HTTP Error 404: Not Found
```

**Comment by KeizerDev** [comment]
```
    print m.get_release_by_id("1a1387bd-ae1f-3024-8618-eeb2249f5538", includes=["artists", "recordings"])
```

**Comment by mineo** [comment]
Well, that's not a release mbid that's associated with any release: https://musicbrainz.org/release/1a1387bd-ae1f-3024-8618-eeb2249f5538, but it seems to be a release group id: https://musicbrainz.org/release-group/1a1387bd-ae1f-3024-8618-eeb2249f5538. Use [get_release_group_by_id](https://python-musicbrainzngs.readthedocs.org/en/latest/api/#musicbrainzngs.get_release_group_by_id) and everything will be fine :)

**Comment by KeizerDev** [comment]
Thanks! :smile:
