### ISSUE TITLE
`UsageError: authorization required; use auth(user, pass) first` when running tests

### ISSUE THREAD

**Issue by alastair** [alastair/python-musicbrainzngs#211]
Reported in Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=842205

```
  ======================================================================
  ERROR: test_submit_single_tag (test.test_submit.SubmitTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "test/test_submit.py", line 30, in test_submit_single_tag
      musicbrainz.submit_tags(artist_tags={"mbid": "single"})
    File "/home/lamby/temp/cdt.20161026221923.SWyGOiHnAI.db.musicbrainzngs/musicbrainzngs-0.6/.pybuild/pythonX.Y_2.7/build/musicbrainzngs/musicbrainz.py", line 1310, in submit_tags
      return _do_mb_post("tag", query)
    File "/home/lamby/temp/cdt.20161026221923.SWyGOiHnAI.db.musicbrainzngs/musicbrainzngs-0.6/.pybuild/pythonX.Y_2.7/build/musicbrainzngs/musicbrainz.py", line 785, in _do_mb_post
      return _mb_request(path, 'POST', AUTH_YES, True, body=body)
    File "/home/lamby/temp/cdt.20161026221923.SWyGOiHnAI.db.musicbrainzngs/musicbrainzngs-0.6/.pybuild/pythonX.Y_2.7/build/musicbrainzngs/musicbrainz.py", line 400, in __call__
      return self.fun(*args, **kwargs)
    File "/home/lamby/temp/cdt.20161026221923.SWyGOiHnAI.db.musicbrainzngs/musicbrainzngs-0.6/.pybuild/pythonX.Y_2.7/build/musicbrainzngs/musicbrainz.py", line 647, in _mb_request
      raise UsageError("authorization required; "
  UsageError: authorization required; use auth(user, pass) first
  
  ======================================================================
  ERROR: test_submit_tags (test.test_submit.SubmitTest)
  ----------------------------------------------------------------------
  Traceback (most recent call last):
    File "test/test_submit.py", line 19, in test_submit_tags
      musicbrainz.submit_tags(artist_tags={"mbid": ["one", "two"]})
    File "/home/lamby/temp/cdt.20161026221923.SWyGOiHnAI.db.musicbrainzngs/musicbrainzngs-0.6/.pybuild/pythonX.Y_2.7/build/musicbrainzngs/musicbrainz.py", line 1310, in submit_tags
      return _do_mb_post("tag", query)
    File "/home/lamby/temp/cdt.20161026221923.SWyGOiHnAI.db.musicbrainzngs/musicbrainzngs-0.6/.pybuild/pythonX.Y_2.7/build/musicbrainzngs/musicbrainz.py", line 785, in _do_mb_post
      return _mb_request(path, 'POST', AUTH_YES, True, body=body)
    File "/home/lamby/temp/cdt.20161026221923.SWyGOiHnAI.db.musicbrainzngs/musicbrainzngs-0.6/.pybuild/pythonX.Y_2.7/build/musicbrainzngs/musicbrainz.py", line 400, in __call__
      return self.fun(*args, **kwargs)
    File "/home/lamby/temp/cdt.20161026221923.SWyGOiHnAI.db.musicbrainzngs/musicbrainzngs-0.6/.pybuild/pythonX.Y_2.7/build/musicbrainzngs/musicbrainz.py", line 647, in _mb_request
      raise UsageError("authorization required; "
  UsageError: authorization required; use auth(user, pass) first
```

I had a look at this issue and it seems that our tests may not be 100% independent - sometimes these tests succeed when when they run in a particular order, but not when run independently

**Comment by mineo** [comment]
I just ran all test files on their own with

```bash
for i in test/test_*.py; do
   python -m unittest $(basename ${i/\//.} .py)
done
```

and it looks like `test_submit.py` is the only one that fails. It seems to require `test_requests.py` (or maybe other that make the correct calls) to have run before.
