### ISSUE TITLE
_caa_request fails to decode json response

### ISSUE THREAD

**Issue by wannabesrevenge** [alastair/python-musicbrainzngs#215]
```
>import musicbrainzngs as mb
>mb.get_release_group_image_list('2a7155f4-77d6-3f94-a0f6-d47f363b8d2c')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/site-packages/musicbrainzngs/caa.py", line 116, in get_release_group_image_list
    return _caa_request(releasegroupid, entitytype="release-group")
  File "/usr/lib/python3.5/site-packages/musicbrainzngs/caa.py", line 81, in _caa_request
    return json.loads(resp)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

```

line 81 in caa.py causes this failure. The HTTP response is a byte array. The byte array needs to be decoded to a string and then JSON loaded. I'm not sure if the response is always a byte array in all situations, but this case is broken.

**Comment by mineo** [comment]
See #208.
