### ISSUE TITLE
submit_isrcs() results in AuthenticationError: caused by: HTTP Error 401: digest auth failed

### ISSUE THREAD

**Issue by augustjanse** [alastair/python-musicbrainzngs#220]
This error is generated from both [isrcsubmit](https://github.com/JonnyJD/musicbrainz-isrcsubmit) and [eac-cue-submit-isrc.py](https://gist.github.com/LordSputnik/7500554). Placed the issue here since both use `musicbrainzngs`. Might be an issue even higher up, though.

Tried on both a Windows 10 PC and a Linux laptop. Only tried one MusicBrainz user.

Without looking too deeply into it, I figure the cause might be one of the following:

1. I have a space in my username
2. I have previously changed my username

Error messages:

isrcsubmit:
`ERROR: Invalid credentials: caused by: HTTP Error 401: digest auth failed`

eac-cue-submit-isrc.py:
```
Traceback (most recent call last):
  File "eac-cue-submit-isrc.py", line 98, in <module>
    mb.submit_isrcs(submit_dict)
  File "C:\Python27\lib\site-packages\musicbrainzngs\musicbrainz.py", line 1291,
 in submit_isrcs
    return _do_mb_post("recording", query)
  File "C:\Python27\lib\site-packages\musicbrainzngs\musicbrainz.py", line 785,
in _do_mb_post
    return _mb_request(path, 'POST', AUTH_YES, True, body=body)
  File "C:\Python27\lib\site-packages\musicbrainzngs\musicbrainz.py", line 400,
in __call__
    return self.fun(*args, **kwargs)
  File "C:\Python27\lib\site-packages\musicbrainzngs\musicbrainz.py", line 673,
in _mb_request
    resp = _safe_read(opener, req, body)
  File "C:\Python27\lib\site-packages\musicbrainzngs\musicbrainz.py", line 491,
in _safe_read
    raise AuthenticationError(cause=exc)
musicbrainzngs.musicbrainz.AuthenticationError: caused by: HTTP Error 401: diges
t auth failed
```

**Comment by augustjanse** [comment]
Submitted this as a [web service bug](https://tickets.metabrainz.org/browse/MBS-9384) on JIRA.

**Comment by augustjanse** [comment]
Was a web service bug.
